export const options = 
[
    { value: '3D printing', label: '3D printing' },
    { value: 'Acting', label: 'Acting' },
    { value: 'Aeromodeling', label: 'Aeromodeling' },
    { value: 'Air sports', label: 'Air sports' },
    { value: 'Airbrushing', label: 'Airbrushing' },
    { value: 'Aircraft Spotting', label: 'Aircraft Spotting' },
    { value: 'Airsoft', label: 'Airsoft' },
    { value: 'Airsofting', label: 'Airsofting' },
    { value: 'Amateur astronomy', label: 'Amateur astronomy' },
    { value: 'Amateur geology', label: 'Amateur geology' },
    { value: 'Amateur Radio', label: 'Amateur Radio' },
    { value: 'American football', label: 'American football' },
    { value: 'Animal fancy', label: 'Animal fancy' },
    { value: 'Animals/pets/dogs', label: 'Animals/pets/dogs' },
    { value: 'Antiquing', label: 'Antiquing' },
    { value: 'Antiquities', label: 'Antiquities' },
    { value: 'Aqua-lung', label: 'Aqua-lung' },
    { value: 'Aquarium (Freshwater & Saltwater)', label: 'Aquarium (Freshwater & Saltwater)' },
    { value: 'Archery', label: 'Archery' },
    { value: 'Art collecting', label: 'Art collecting' },
    { value: 'Arts', label: 'Arts' },
    { value: 'Association football', label: 'Association football' },
    { value: 'Astrology', label: 'Astrology' },
    { value: 'Astronomy', label: 'Astronomy' },
    { value: 'Audiophilia', label: 'Audiophilia' },
    { value: 'Australian rules football', label: 'Australian rules football' },
    { value: 'Auto audiophilia', label: 'Auto audiophilia' },
    { value: 'Auto racing', label: 'Auto racing' },
    { value: 'Backgammon', label: 'Backgammon' },
    { value: 'Backpacking', label: 'Backpacking' },
    { value: 'Badminton', label: 'Badminton' },
    { value: 'Base Jumping', label: 'Base Jumping' },
    { value: 'Baseball', label: 'Baseball' },
    { value: 'Basketball', label: 'Basketball' },
    { value: 'Baton Twirling', label: 'Baton Twirling' },
    { value: 'Beach Volleyball', label: 'Beach Volleyball' },
    { value: 'Beach/Sun tanning', label: 'Beach/Sun tanning' },
    { value: 'Beachcombing', label: 'Beachcombing' },
    { value: 'Beadwork', label: 'Beadwork' },
    { value: 'Beatboxing', label: 'Beatboxing' },
    { value: 'Becoming A Child Advocate', label: 'Becoming A Child Advocate' },
    { value: 'Beekeeping', label: 'Beekeeping' },
    { value: 'Bell Ringing', label: 'Bell Ringing' },
    { value: 'Belly Dancing', label: 'Belly Dancing' },
    { value: 'Bicycle Polo', label: 'Bicycle Polo' },
    { value: 'Bicycling', label: 'Bicycling' },
    { value: 'Billiards', label: 'Billiards' },
    { value: 'Bird watching', label: 'Bird watching' },
    { value: 'Birding', label: 'Birding' },
    { value: 'Birdwatching', label: 'Birdwatching' },
    { value: 'Blacksmithing', label: 'Blacksmithing' },
    { value: 'Blogging', label: 'Blogging' },
    { value: 'BMX', label: 'BMX' },
    { value: 'Board games', label: 'Board games' },
    { value: 'Board sports', label: 'Board sports' },
    { value: 'BoardGames', label: 'BoardGames' },
    { value: 'Boating', label: 'Boating' },
    { value: 'Body Building', label: 'Body Building' },
    { value: 'Bodybuilding', label: 'Bodybuilding' },
    { value: 'Bonsai Tree', label: 'Bonsai Tree' },
    { value: 'Book collecting', label: 'Book collecting' },
    { value: 'Bookbinding', label: 'Bookbinding' },
    { value: 'Boomerangs', label: 'Boomerangs' },
    { value: 'Bowling', label: 'Bowling' },
    { value: 'Boxing', label: 'Boxing' },
    { value: 'Brazilian jiu-jitsu', label: 'Brazilian jiu-jitsu' },
    { value: 'Breakdancing', label: 'Breakdancing' },
    { value: 'Brewing Beer', label: 'Brewing Beer' },
    { value: 'Bridge', label: 'Bridge' },
    { value: 'Bridge Building', label: 'Bridge Building' },
    { value: 'Bringing Food To The Disabled', label: 'Bringing Food To The Disabled' },
    { value: 'Building A House For Habitat For Humanity', label: 'Building A House For Habitat For Humanity' },
    { value: 'Building Dollhouses', label: 'Building Dollhouses' },
    { value: 'Bus spotting', label: 'Bus spotting' },
    { value: 'Butterfly Watching', label: 'Butterfly Watching' },
    { value: 'Button Collecting', label: 'Button Collecting' },
    { value: 'Cake Decorating', label: 'Cake Decorating' },
    { value: 'Calligraphy', label: 'Calligraphy' },
    { value: 'Camping', label: 'Camping' },
    { value: 'Candle making', label: 'Candle making' },
    { value: 'Canoeing', label: 'Canoeing' },
    { value: 'Car Racing', label: 'Car Racing' },
    { value: 'Card collecting', label: 'Card collecting' },
    { value: 'Cartooning', label: 'Cartooning' },
    { value: 'Casino Gambling', label: 'Casino Gambling' },
    { value: 'Cave Diving', label: 'Cave Diving' },
    { value: 'Ceramics', label: 'Ceramics' },
    { value: 'Cheerleading', label: 'Cheerleading' },
    { value: 'Chess', label: 'Chess' },
    { value: 'Church/church activities', label: 'Church/church activities' },
    { value: 'Cigar Smoking', label: 'Cigar Smoking' },
    { value: 'Climbing', label: 'Climbing' },
    { value: 'Cloud Watching', label: 'Cloud Watching' },
    { value: 'Coin Collecting', label: 'Coin Collecting' },
    { value: 'Collecting', label: 'Collecting' },
    { value: 'Collecting Antiques', label: 'Collecting Antiques' },
    { value: 'Collecting Artwork', label: 'Collecting Artwork' },
    { value: 'Collecting Hats', label: 'Collecting Hats' },
    { value: 'Collecting Music Albums', label: 'Collecting Music Albums' },
    { value: 'Collecting RPM Records', label: 'Collecting RPM Records' },
    { value: 'Collecting Sports Cards (Baseball, Football, Basketball, Hockey)', label: 'Collecting Sports Cards (Baseball, Football, Basketball, Hockey)' },
    { value: 'Collecting Swords', label: 'Collecting Swords' },
    { value: 'Color guard', label: 'Color guard' },
    { value: 'Coloring', label: 'Coloring' },
    { value: 'Comic book collecting', label: 'Comic book collecting' },
    { value: 'Compose Music', label: 'Compose Music' },
    { value: 'Computer activities', label: 'Computer activities' },
    { value: 'Computer programming', label: 'Computer programming' },
    { value: 'Conworlding', label: 'Conworlding' },
    { value: 'Cooking', label: 'Cooking' },
    { value: 'Cosplay', label: 'Cosplay' },
    { value: 'Cosplaying', label: 'Cosplaying' },
    { value: 'Couponing', label: 'Couponing' },
    { value: 'Crafts', label: 'Crafts' },
    { value: 'Crafts (unspecified)', label: 'Crafts (unspecified)' },
    { value: 'Creative writing', label: 'Creative writing' },
    { value: 'Cricket', label: 'Cricket' },
    { value: 'Crochet', label: 'Crochet' },
    { value: 'Crocheting', label: 'Crocheting' },
    { value: 'Cross-Stitch', label: 'Cross-Stitch' },
    { value: 'Crossword Puzzles', label: 'Crossword Puzzles' },
    { value: 'Cryptography', label: 'Cryptography' },
    { value: 'Curling', label: 'Curling' },
    { value: 'Cycling', label: 'Cycling' },
    { value: 'Dance', label: 'Dance' },
    { value: 'Dancing', label: 'Dancing' },
    { value: 'Darts', label: 'Darts' },
    { value: 'Debate', label: 'Debate' },
    { value: 'Deltiology (postcard collecting)', label: 'Deltiology (postcard collecting)' },
    { value: 'Diecast Collectibles', label: 'Diecast Collectibles' },
    { value: 'Digital arts', label: 'Digital arts' },
    { value: 'Digital Photography', label: 'Digital Photography' },
    { value: 'Disc golf', label: 'Disc golf' },
    { value: 'Do it yourself', label: 'Do it yourself' },
    { value: 'Dodgeball', label: 'Dodgeball' },
    { value: 'Dog sport', label: 'Dog sport' },
    { value: 'Dolls', label: 'Dolls' },
    { value: 'Dominoes', label: 'Dominoes' },
    { value: 'Dowsing', label: 'Dowsing' },
    { value: 'Drama', label: 'Drama' },
    { value: 'Drawing', label: 'Drawing' },
    { value: 'Driving', label: 'Driving' },
    { value: 'Dumpster Diving', label: 'Dumpster Diving' },
    { value: 'Eating out', label: 'Eating out' },
    { value: 'Educational Courses', label: 'Educational Courses' },
    { value: 'Electronics', label: 'Electronics' },
    { value: 'Element collecting', label: 'Element collecting' },
    { value: 'Embroidery', label: 'Embroidery' },
    { value: 'Entertaining', label: 'Entertaining' },
    { value: 'Equestrianism', label: 'Equestrianism' },
    { value: 'Exercise (aerobics, weights)', label: 'Exercise (aerobics, weights)' },
    { value: 'Exhibition drill', label: 'Exhibition drill' },
    { value: 'Falconry', label: 'Falconry' },
    { value: 'Fast cars', label: 'Fast cars' },
    { value: 'Felting', label: 'Felting' },
    { value: 'Fencing', label: 'Fencing' },
    { value: 'Field hockey', label: 'Field hockey' },
    { value: 'Figure skating', label: 'Figure skating' },
    { value: 'Fire Poi', label: 'Fire Poi' },
    { value: 'Fishing', label: 'Fishing' },
    { value: 'Fishkeeping', label: 'Fishkeeping' },
    { value: 'Flag Football', label: 'Flag Football' },
    { value: 'Floorball', label: 'Floorball' },
    { value: 'Floral Arrangements', label: 'Floral Arrangements' },
    { value: 'Flower arranging', label: 'Flower arranging' },
    { value: 'Flower collecting and pressing', label: 'Flower collecting and pressing' },
    { value: 'Fly Tying', label: 'Fly Tying' },
    { value: 'Flying', label: 'Flying' },
    { value: 'Footbag', label: 'Footbag' },
    { value: 'Football', label: 'Football' },
    { value: 'Foraging', label: 'Foraging' },
    { value: 'Foreign language learning', label: 'Foreign language learning' },
    { value: 'Fossil hunting', label: 'Fossil hunting' },
    { value: 'Four Wheeling', label: 'Four Wheeling' },
    { value: 'Freshwater Aquariums', label: 'Freshwater Aquariums' },
    { value: 'Frisbee Golf – Frolf', label: 'Frisbee Golf – Frolf' },
    { value: 'Gambling', label: 'Gambling' },
    { value: 'Games', label: 'Games' },
    { value: 'Gaming (tabletop games and role-playing games)', label: 'Gaming (tabletop games and role-playing games)' },
    { value: 'Garage Saleing', label: 'Garage Saleing' },
    { value: 'Gardening', label: 'Gardening' },
    { value: 'Genealogy', label: 'Genealogy' },
    { value: 'Geocaching', label: 'Geocaching' },
    { value: 'Ghost hunting', label: 'Ghost hunting' },
    { value: 'Glassblowing', label: 'Glassblowing' },
    { value: 'Glowsticking', label: 'Glowsticking' },
    { value: 'Gnoming', label: 'Gnoming' },
    { value: 'Go', label: 'Go' },
    { value: 'Go Kart Racing', label: 'Go Kart Racing' },
    { value: 'Going to movies', label: 'Going to movies' },
    { value: 'Golf', label: 'Golf' },
    { value: 'Golfing', label: 'Golfing' },
    { value: 'Gongoozling', label: 'Gongoozling' },
    { value: 'Graffiti', label: 'Graffiti' },
    { value: 'Grip Strength', label: 'Grip Strength' },
    { value: 'Guitar', label: 'Guitar' },
    { value: 'Gun Collecting', label: 'Gun Collecting' },
    { value: 'Gunsmithing', label: 'Gunsmithing' },
    { value: 'Gymnastics', label: 'Gymnastics' },
    { value: 'Gyotaku', label: 'Gyotaku' },
    { value: 'Handball', label: 'Handball' },
    { value: 'Handwriting Analysis', label: 'Handwriting Analysis' },
    { value: 'Hang gliding', label: 'Hang gliding' },
    { value: 'Herping', label: 'Herping' },
    { value: 'Hiking', label: 'Hiking' },
    { value: 'Home Brewing', label: 'Home Brewing' },
    { value: 'Home Repair', label: 'Home Repair' },
    { value: 'Home Theater', label: 'Home Theater' },
    { value: 'Homebrewing', label: 'Homebrewing' },
    { value: 'Hooping', label: 'Hooping' },
    { value: 'Horse riding', label: 'Horse riding' },
    { value: 'Hot air ballooning', label: 'Hot air ballooning' },
    { value: 'Hula Hooping', label: 'Hula Hooping' },
    { value: 'Hunting', label: 'Hunting' },
    { value: 'Ice hockey', label: 'Ice hockey' },
    { value: 'Ice skating', label: 'Ice skating' },
    { value: 'Iceskating', label: 'Iceskating' },
    { value: 'Illusion', label: 'Illusion' },
    { value: 'Impersonations', label: 'Impersonations' },
    { value: 'Inline skating', label: 'Inline skating' },
    { value: 'Insect collecting', label: 'Insect collecting' },
    { value: 'Internet', label: 'Internet' },
    { value: 'Inventing', label: 'Inventing' },
    { value: 'Jet Engines', label: 'Jet Engines' },
    { value: 'Jewelry Making', label: 'Jewelry Making' },
    { value: 'Jigsaw Puzzles', label: 'Jigsaw Puzzles' },
    { value: 'Jogging', label: 'Jogging' },
    { value: 'Judo', label: 'Judo' },
    { value: 'Juggling', label: 'Juggling' },
    { value: 'Jukskei', label: 'Jukskei' },
    { value: 'Jump Roping', label: 'Jump Roping' },
    { value: 'Kabaddi', label: 'Kabaddi' },
    { value: 'Kart racing', label: 'Kart racing' },
    { value: 'Kayaking', label: 'Kayaking' },
    { value: 'Keep A Journal', label: 'Keep A Journal' },
    { value: 'Kitchen Chemistry', label: 'Kitchen Chemistry' },
    { value: 'Kite Boarding', label: 'Kite Boarding' },
    { value: 'Kite flying', label: 'Kite flying' },
    { value: 'Kites', label: 'Kites' },
    { value: 'Kitesurfing', label: 'Kitesurfing' },
    { value: 'Knapping', label: 'Knapping' },
    { value: 'Knife making', label: 'Knife making' },
    { value: 'Knife throwing', label: 'Knife throwing' },
    { value: 'Knitting', label: 'Knitting' },
    { value: 'Knotting', label: 'Knotting' },
    { value: 'Lacemaking', label: 'Lacemaking' },
    { value: 'Lacrosse', label: 'Lacrosse' },
    { value: 'Lapidary', label: 'Lapidary' },
    { value: 'LARPing', label: 'LARPing' },
    { value: 'Laser tag', label: 'Laser tag' },
    { value: 'Lasers', label: 'Lasers' },
    { value: 'Lawn Darts', label: 'Lawn Darts' },
    { value: 'Learn to Play Poker', label: 'Learn to Play Poker' },
    { value: 'Learning A Foreign Language', label: 'Learning A Foreign Language' },
    { value: 'Learning An Instrument', label: 'Learning An Instrument' },
    { value: 'Learning To Pilot A Plane', label: 'Learning To Pilot A Plane' },
    { value: 'Leather crafting', label: 'Leather crafting' },
    { value: 'Leathercrafting', label: 'Leathercrafting' },
    { value: 'Lego building', label: 'Lego building' },
    { value: 'Legos', label: 'Legos' },
    { value: 'Letterboxing', label: 'Letterboxing' },
    { value: 'Listening to music', label: 'Listening to music' },
    { value: 'Locksport', label: 'Locksport' },
    { value: 'Machining', label: 'Machining' },
    { value: 'Macramé', label: 'Macramé' },
    { value: 'Macrame', label: 'Macrame' },
    { value: 'Magic', label: 'Magic' },
    { value: 'Mahjong', label: 'Mahjong' },
    { value: 'Making Model Cars', label: 'Making Model Cars' },
    { value: 'Marbles', label: 'Marbles' },
    { value: 'Marksmanship', label: 'Marksmanship' },
    { value: 'Martial arts', label: 'Martial arts' },
    { value: 'Matchstick Modeling', label: 'Matchstick Modeling' },
    { value: 'Meditation', label: 'Meditation' },
    { value: 'Metal detecting', label: 'Metal detecting' },
    { value: 'Meteorology', label: 'Meteorology' },
    { value: 'Microscopy', label: 'Microscopy' },
    { value: 'Mineral collecting', label: 'Mineral collecting' },
    { value: 'Model aircraft', label: 'Model aircraft' },
    { value: 'Model building', label: 'Model building' },
    { value: 'Model Railroading', label: 'Model Railroading' },
    { value: 'Model Rockets', label: 'Model Rockets' },
    { value: 'Modeling Ships', label: 'Modeling Ships' },
    { value: 'Models', label: 'Models' },
    { value: 'Motor sports', label: 'Motor sports' },
    { value: 'Motorcycles', label: 'Motorcycles' },
    { value: 'Mountain Biking', label: 'Mountain Biking' },
    { value: 'Mountain Climbing', label: 'Mountain Climbing' },
    { value: 'Mountaineering', label: 'Mountaineering' },
    { value: 'Movie and movie memorabilia collecting', label: 'Movie and movie memorabilia collecting' },
    { value: 'Mushroom hunting/Mycology', label: 'Mushroom hunting/Mycology' },
    { value: 'Musical Instruments', label: 'Musical Instruments' },
    { value: 'Nail Art', label: 'Nail Art' },
    { value: 'Needlepoint', label: 'Needlepoint' },
    { value: 'Netball', label: 'Netball' },
    { value: 'Nordic skating', label: 'Nordic skating' },
    { value: 'Orienteering', label: 'Orienteering' },
    { value: 'Origami', label: 'Origami' },
    { value: 'Owning An Antique Car', label: 'Owning An Antique Car' },
    { value: 'Paintball', label: 'Paintball' },
    { value: 'Painting', label: 'Painting' },
    { value: 'Papermache', label: 'Papermache' },
    { value: 'Papermaking', label: 'Papermaking' },
    { value: 'Parachuting', label: 'Parachuting' },
    { value: 'Paragliding or Power Paragliding', label: 'Paragliding or Power Paragliding' },
    { value: 'Parkour', label: 'Parkour' },
    { value: 'People Watching', label: 'People Watching' },
    { value: 'Photography', label: 'Photography' },
    { value: 'Piano', label: 'Piano' },
    { value: 'Pigeon racing', label: 'Pigeon racing' },
    { value: 'Pinochle', label: 'Pinochle' },
    { value: 'Pipe Smoking', label: 'Pipe Smoking' },
    { value: 'Planking', label: 'Planking' },
    { value: 'Playing music', label: 'Playing music' },
    { value: 'Playing musical instruments', label: 'Playing musical instruments' },
    { value: 'Playing team sports', label: 'Playing team sports' },
    { value: 'Poker', label: 'Poker' },
    { value: 'Pole Dancing', label: 'Pole Dancing' },
    { value: 'Polo', label: 'Polo' },
    { value: 'Pottery', label: 'Pottery' },
    { value: 'Powerboking', label: 'Powerboking' },
    { value: 'Protesting', label: 'Protesting' },
    { value: 'Puppetry', label: 'Puppetry' },
    { value: 'Puzzles', label: 'Puzzles' },
    { value: 'Pyrotechnics', label: 'Pyrotechnics' },
    { value: 'Quilting', label: 'Quilting' },
    { value: 'R/C Boats', label: 'R/C Boats' },
    { value: 'R/C Cars', label: 'R/C Cars' },
    { value: 'R/C Helicopters', label: 'R/C Helicopters' },
    { value: 'R/C Planes', label: 'R/C Planes' },
    { value: 'Racing Pigeons', label: 'Racing Pigeons' },
    { value: 'Racquetball', label: 'Racquetball' },
    { value: 'Radio-controlled car racing', label: 'Radio-controlled car racing' },
    { value: 'Rafting', label: 'Rafting' },
    { value: 'Railfans', label: 'Railfans' },
    { value: 'Rappelling', label: 'Rappelling' },
    { value: 'Rapping', label: 'Rapping' },
    { value: 'Reading', label: 'Reading' },
    { value: 'Reading To The Elderly', label: 'Reading To The Elderly' },
    { value: 'Record collecting', label: 'Record collecting' },
    { value: 'Relaxing', label: 'Relaxing' },
    { value: 'Renaissance Faire', label: 'Renaissance Faire' },
    { value: 'Renting movies', label: 'Renting movies' },
    { value: 'Rescuing Abused Or Abandoned Animals', label: 'Rescuing Abused Or Abandoned Animals' },
    { value: 'Robotics', label: 'Robotics' },
    { value: 'Rock balancing', label: 'Rock balancing' },
    { value: 'Rock climbing', label: 'Rock climbing' },
    { value: 'Rock Collecting', label: 'Rock Collecting' },
    { value: 'Rockets', label: 'Rockets' },
    { value: 'Rocking AIDS Babies', label: 'Rocking AIDS Babies' },
    { value: 'Roleplaying', label: 'Roleplaying' },
    { value: 'Roller derby', label: 'Roller derby' },
    { value: 'Roller skating', label: 'Roller skating' },
    { value: 'Rugby', label: 'Rugby' },
    { value: 'Rugby league football', label: 'Rugby league football' },
    { value: 'Running', label: 'Running' },
    { value: 'Sailing', label: 'Sailing' },
    { value: 'Saltwater Aquariums', label: 'Saltwater Aquariums' },
    { value: 'Sand art', label: 'Sand art' },
    { value: 'Sand Castles', label: 'Sand Castles' },
    { value: 'Scrapbooking', label: 'Scrapbooking' },
    { value: 'Scuba diving', label: 'Scuba diving' },
    { value: 'Sculling or Rowing', label: 'Sculling or Rowing' },
    { value: 'Sculpting', label: 'Sculpting' },
    { value: 'Sea glass collecting', label: 'Sea glass collecting' },
    { value: 'Seashell collecting', label: 'Seashell collecting' },
    { value: 'Self Defense', label: 'Self Defense' },
    { value: 'Sewing', label: 'Sewing' },
    { value: 'Shark Fishing', label: 'Shark Fishing' },
    { value: 'Shooting', label: 'Shooting' },
    { value: 'Shooting sport', label: 'Shooting sport' },
    { value: 'Shopping', label: 'Shopping' },
    { value: 'Shortwave listening', label: 'Shortwave listening' },
    { value: 'Singing', label: 'Singing' },
    { value: 'Singing In Choir', label: 'Singing In Choir' },
    { value: 'Skateboarding', label: 'Skateboarding' },
    { value: 'Skeet Shooting', label: 'Skeet Shooting' },
    { value: 'Sketching', label: 'Sketching' },
    { value: 'Skiing', label: 'Skiing' },
    { value: 'Skimboarding', label: 'Skimboarding' },
    { value: 'Sky Diving', label: 'Sky Diving' },
    { value: 'Skydiving', label: 'Skydiving' },
    { value: 'Slack Lining', label: 'Slack Lining' },
    { value: 'Slacklining', label: 'Slacklining' },
    { value: 'Sleeping', label: 'Sleeping' },
    { value: 'Slingshots', label: 'Slingshots' },
    { value: 'Slot car racing', label: 'Slot car racing' },
    { value: 'Snorkeling', label: 'Snorkeling' },
    { value: 'Snowboarding', label: 'Snowboarding' },
    { value: 'Soap Making', label: 'Soap Making' },
    { value: 'Soapmaking', label: 'Soapmaking' },
    { value: 'Soccer', label: 'Soccer' },
    { value: 'Socializing with friends/neighbors', label: 'Socializing with friends/neighbors' },
    { value: 'Speed Cubing (rubix cube)', label: 'Speed Cubing (rubix cube)' },
    { value: 'Speed skating', label: 'Speed skating' },
    { value: 'Spelunkering', label: 'Spelunkering' },
    { value: 'Spending time with family/kids', label: 'Spending time with family/kids' },
    { value: 'Sports', label: 'Sports' },
    { value: 'Squash', label: 'Squash' },
    { value: 'Stamp Collecting', label: 'Stamp Collecting' },
    { value: 'Stand-up comedy', label: 'Stand-up comedy' },
    { value: 'Stone collecting', label: 'Stone collecting' },
    { value: 'Stone skipping', label: 'Stone skipping' },
    { value: 'Storm Chasing', label: 'Storm Chasing' },
    { value: 'Storytelling', label: 'Storytelling' },
    { value: 'String Figures', label: 'String Figures' },
    { value: 'Sudoku', label: 'Sudoku' },
    { value: 'Surf Fishing', label: 'Surf Fishing' },
    { value: 'Surfing', label: 'Surfing' },
    { value: 'Survival', label: 'Survival' },
    { value: 'Swimming', label: 'Swimming' },
    { value: 'Table football', label: 'Table football' },
    { value: 'Table tennis', label: 'Table tennis' },
    { value: 'Taekwondo', label: 'Taekwondo' },
    { value: 'Tai chi', label: 'Tai chi' },
    { value: 'Tatting', label: 'Tatting' },
    { value: 'Taxidermy', label: 'Taxidermy' },
    { value: 'Tea Tasting', label: 'Tea Tasting' },
    { value: 'Tennis', label: 'Tennis' },
    { value: 'Tesla Coils', label: 'Tesla Coils' },
    { value: 'Tetris', label: 'Tetris' },
    { value: 'Textiles', label: 'Textiles' },
    { value: 'Texting', label: 'Texting' },
    { value: 'Tombstone Rubbing', label: 'Tombstone Rubbing' },
    { value: 'Tool Collecting', label: 'Tool Collecting' },
    { value: 'Tour skating', label: 'Tour skating' },
    { value: 'Toy Collecting', label: 'Toy Collecting' },
    { value: 'Train Collecting', label: 'Train Collecting' },
    { value: 'Train Spotting', label: 'Train Spotting' },
    { value: 'Trainspotting', label: 'Trainspotting' },
    { value: 'Traveling', label: 'Traveling' },
    { value: 'Treasure Hunting', label: 'Treasure Hunting' },
    { value: 'Trekkie', label: 'Trekkie' },
    { value: 'Triathlon', label: 'Triathlon' },
    { value: 'Tutoring Children', label: 'Tutoring Children' },
    { value: 'TV watching', label: 'TV watching' },
    { value: 'Ultimate Frisbee', label: 'Ultimate Frisbee' },
    { value: 'Urban exploration', label: 'Urban exploration' },
    { value: 'Vehicle restoration', label: 'Vehicle restoration' },
    { value: 'Video game collecting', label: 'Video game collecting' },
    { value: 'Video Games', label: 'Video Games' },
    { value: 'Video gaming', label: 'Video gaming' },
    { value: 'Videophilia', label: 'Videophilia' },
    { value: 'Vintage cars', label: 'Vintage cars' },
    { value: 'Violin', label: 'Violin' },
    { value: 'Volleyball', label: 'Volleyball' },
    { value: 'Volunteer', label: 'Volunteer' },
    { value: 'Walking', label: 'Walking' },
    { value: 'Warhammer', label: 'Warhammer' },
    { value: 'Watching movies', label: 'Watching movies' },
    { value: 'Watching sporting events', label: 'Watching sporting events' },
    { value: 'Water sports', label: 'Water sports' },
    { value: 'Weather Watcher', label: 'Weather Watcher' },
    { value: 'Web surfing', label: 'Web surfing' },
    { value: 'Weightlifting', label: 'Weightlifting' },
    { value: 'Windsurfing', label: 'Windsurfing' },
    { value: 'Wine Making', label: 'Wine Making' },
    { value: 'Wingsuit Flying', label: 'Wingsuit Flying' },
    { value: 'Wood carving', label: 'Wood carving' },
    { value: 'Woodworking', label: 'Woodworking' },
    { value: 'Working In A Food Pantry', label: 'Working In A Food Pantry' },
    { value: 'Working on cars', label: 'Working on cars' },
    { value: 'World Record Breaking', label: 'World Record Breaking' },
    { value: 'Worldbuilding', label: 'Worldbuilding' },
    { value: 'Wrestling', label: 'Wrestling' },
    { value: 'Writing', label: 'Writing' },
    { value: 'Writing Music', label: 'Writing Music' },
    { value: 'Writing Songs', label: 'Writing Songs' },
    { value: 'Yo-yoing', label: 'Yo-yoing' },
    { value: 'Yoga', label: 'Yoga' },
    { value: 'YoYo', label: 'YoYo' },
    { value: 'Ziplining', label: 'Ziplining' },
    { value: 'Zumba', label: 'Zumba' }    
]